version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
  bot:
    volumes:
      - .:/app
    container_name: discord-bot
    depends_on:
      - db
    build: .
    env_file:
      .env

volumes:
  db-data: